ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: microsoftedge
    version: latest
  - name: internet explorer
    version: 10..latest
  - name: android
    version: ['4.4', '5.1']
  - name: safari
    version: 6..latest
  - name: iphone
    version: ['6.0', '7.0', '7.1' '8.0', '8.4..latest']
